### ISSUE TITLE
Error with urls_from_html() on some websites

### ISSUE THREAD

**Issue by charlespv** [medialab/ural#29]
Message error
```
...\ural\urls_from_html.py in urls_from_html(string)
     29     for a_tag in re.finditer(HTML_URL_RE, string):
     30         url = a_tag.group(3)
---> 31         yield clean_link(url)

...\ural\urls_from_html.py in clean_link(link)
     13 def clean_link(link):
     14     """Removes leading and trailing whitespace and punctuation"""
---> 15     return link.strip("\t\r\n '\"\x0c")
     16 
     17 

AttributeError: 'NoneType' object has no attribute 'strip'
```
List of website where error happened
- https://www.privacyshield.gov/participant?id=a2zt000000001K2AAI
- https://developer.github.com/v3/users/
- https://www.privacyshield.gov/
- https://www.jamsadr.com/file-an-eu-us-privacy-shield-claim
- https://www.privacyshield.gov/article?id=ANNEX-I-introduction
- https://creativecommons.org/publicdomain/zero/1.0/
- https://github.community
- https://twitter.com/github
- https://www.facebook.com/GitHub

**Comment by oubine** [comment]
This function use HTML_URL_RE pattern below. 
```html
<a\s.*?href=(?:\"([.#]+?)\"|\'([.#]+?)\'|([^\s]+?))(?:>|\s.*?>)(?:.*?)<[/ ]?a>"
```

But, mainly the third option of the regex (`[^\s]+?`) is used to match the tag and then `group(3)` is called on the match to get the url. However when a link is matched thanks to one of the two first options of the regex (`"([.#]+?)\"` or `\'([.#]+?)\'`) then `group(3)` is a `None object` because the link is stored in `group(1)`.
* example: <a href="#">(415) 735-4488</a> match with the first option and then drops an error because group(3) is a NoneType
 
Moreover, at the end of the regex, for the closing tag (`<[/ ]?a>`), the space character should be replace by an `\s` to consider all type of space.

**Comment by boogheta** [comment]
+1

And btw, in most languages, [^\s] can be shortened by simply writing \S

And careful, in python3.4 (I believe), when a match is a None, group(3) crashes instead of returning None (one of the crazy breaking behavior that made this python version quickly be deprecated)
